version: "3.7"
services:
  Spendthrift:
    restart: always
    image: spendthrift
    ports:
      - 8081:8081
    environment:
      - DATABASE_HOST=PostgreSQL
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=spendthrift
      - DATABASE_NAME=spendthrift
      - DATABASE_PASSWORD=spendthrift@dev
      - DATABASE_MAX_CONNECTIONS=4
      - HTTP_SERVER_HOST=0.0.0.0
      - HTTP_SERVER_PORT=8081
    networks:
      - spendthrift-network
    depends_on:
      PostgreSQL:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=1 --output-document=/dev/null http://localhost:8081/health || exit 1
      start_period: 10s
      interval: 5s
      timeout: 1s
      retries: 5

  PostgreSQL:
    restart: always
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - DEBUG=false
      - POSTGRES_USER=spendthrift
      - POSTGRES_PASSWORD=spendthrift@dev
      - POSTGRES_DB=spendthrift
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - spendthrift-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  PGAdmin:
    restart: always
    image: dpage/pgadmin4
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=spendthrift@dev.com
      - PGADMIN_DEFAULT_PASSWORD=spendthrift@dev
    volumes:
      - admin-data:/var/lib/pgadmin
    networks:
      - spendthrift-network
    depends_on:
      PostgreSQL:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost || exit 1
      interval: 10s
      timeout: 5s
      retries: 5

  Prometheus:
    restart: always
    image: prom/prometheus
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9000:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    networks:
      - spendthrift-network

  Grafana:
    restart: always
    image: grafana/grafana-oss
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - spendthrift-network

  PostgresExporter:
    restart: always
    image: quay.io/prometheuscommunity/postgres-exporter
    environment:
      - DATA_SOURCE_URI=PostgreSQL?sslmode=disable
      - DATA_SOURCE_USER=spendthrift
      - DATA_SOURCE_PASS=spendthrift@dev
    networks:
      - spendthrift-network

  Jaeger:
    restart: always
    image: jaegertracing/all-in-one
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    networks:
      - spendthrift-network

volumes:
  admin-data:
    driver: local
  grafana-data:
    driver: local
  postgres-data:
    driver: local
  prometheus-data:
    driver: local

networks:
  spendthrift-network:
    driver: bridge
