version: "3.7"
services:
  Spendthrift:
    restart: always
    image: spendthrift
    ports:
      - 8081:8081
    environment:
      - DATABASE_HOST=PostgreSQL
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=spendthrift
      - DATABASE_NAME=spendthrift
      - DATABASE_PASSWORD=spendthrift@dev
      - DATABASE_MAX_CONNECTIONS=4
      - HTTP_SERVER_HOST=0.0.0.0
      - HTTP_SERVER_PORT=8081
    networks:
      - postgres-network
    depends_on:
      PostgreSQL:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=1 --output-document=/dev/null http://localhost:8081/health || exit 1
      start_period: 10s
      interval: 5s
      timeout: 1s
      retries: 5

  PostgreSQL:
    restart: always
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - DEBUG=false
      - POSTGRES_USER=spendthrift
      - POSTGRES_PASSWORD=spendthrift@dev
      - POSTGRES_DB=spendthrift
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - postgres-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  PGAdmin:
    restart: always
    image: dpage/pgadmin4
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=spendthrift@dev.com
      - PGADMIN_DEFAULT_PASSWORD=spendthrift@dev
    volumes:
      - admin-data:/var/lib/pgadmin
    networks:
      - postgres-network
    depends_on:
      PostgreSQL:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost || exit 1
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  admin-data:
    driver: local
  postgres-data:
    driver: local

networks:
  postgres-network:
    driver: bridge
