name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: openjdk@1.11

      - name: Cache Coursier dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/coursier
          key: ${{ runner.os }}-${{ github.ref }}-coursier
          restore-keys: |
            ${{ runner.os }}-${{ github.ref }}-coursier

      - name: Cache Ivy dependencies
        uses: actions/cache@v2
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-${{ github.ref }}-ivy2
          restore-keys: |
            ${{ runner.os }}-${{ github.ref }}-ivy2

      - name: Set up Mill
        uses: jodersky/setup-mill@v0.2.3

      - name: Check Style
        run: mill all __.checkFormat
