name: Build

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      PostgreSQL:
        image: postgres:14-alpine
        ports:
          - 5432:5432
        env:
          DEBUG: false
          POSTGRES_USER: spendthrift
          POSTGRES_PASSWORD: spendthrift@dev
          POSTGRES_DB: spendthrift
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Scala
        uses: olafurpg/setup-scala@v13
        with:
          java-version: openjdk@1.11

      - name: Cache Coursier dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/coursier
          key: ${{ runner.os }}-${{ github.ref }}-coursier
          restore-keys: |
            ${{ runner.os }}-${{ github.ref }}-coursier

      - name: Cache Ivy dependencies
        uses: actions/cache@v2
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-${{ github.ref }}-ivy2
          restore-keys: |
            ${{ runner.os }}-${{ github.ref }}-ivy2

      - name: Set up Mill
        run: ./millw version

      - name: Build Project
        run: ./millw __.compile

      - name: Check Style
        run: ./millw all __.checkFormat

      - name: Run migrations
        run: ./millw spendthrift.flywayMigrate
        env:
          FLYWAY_URL: "jdbc:postgresql://localhost:5432/spendthrift"
          FLYWAY_USER: spendthrift
          FLYWAY_PASSWORD: "spendthrift@dev"

      - name: Run Tests
        run: ./millw --disable-ticker all __.test
